In [6]:
import numpy as np

In [7]:
print("=" * 60)
print("NUMPY ASSIGNMENT: RETAIL DATA ANALYSIS")
print("=" * 60)

NUMPY ASSIGNMENT: RETAIL DATA ANALYSIS


In [6]:
banking_data = np.array([
    [101, 50000, 720, 20, 3],
    [102, 120000, 810, 45, 8],
    [103, 75000, 690, 15, 5],
    [104, 30000, 650, 10, 2],
    [105, 95000, 770, 25, 6],
    [106, 200000, 850, 60, 12],
    [107, 15000, 600, 5, 1],
    [108, 40000, 710, 18, 4],
    [109, 110000, 790, 40, 9],
    [110, 85000, 730, 30, 7]
])


#ARRAY CREATION AND MANIPULATION

1: Create a 4×4 identity matrix using np.eye()

In [1]:
import numpy as np

identity_matrix = np.eye(4)
print(identity_matrix)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


2: Create an array of 8 zeros using np.zeros()

In [2]:
zeros_array = np.zeros(8)
print(zeros_array)

[0. 0. 0. 0. 0. 0. 0. 0.]


3: Create an array of 6 ones using np.ones()

In [3]:
ones_array = np.ones(6)
print(ones_array)

[1. 1. 1. 1. 1. 1.]


4: Create an array with values from 0 to 15 using np.arange()

In [5]:
range_array = np.arange(16)
print(range_array)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


5: Create an array with 8 evenly spaced values from 0 to 100 using np.linspace()

In [4]:
linspace_array = np.linspace(0, 100, 8)
print(linspace_array)

[  0.          14.28571429  28.57142857  42.85714286  57.14285714
  71.42857143  85.71428571 100.        ]
