In [10]:
import numpy as np


In [11]:
np.random.randint(0,100)

51

In [12]:
# NumPy Arithmetic Functions Example (Single Cell)

import numpy as np

# Creating two arrays
a = np.array([10, 20, 30, 40])
b = np.array([1, 2, 3, 4])

print("Array A:", a)
print("Array B:", b)

# Addition
print("\nAddition (np.add):")
print(np.add(a, b))

# Subtraction
print("\nSubtraction (np.subtract):")
print(np.subtract(a, b))

# Multiplication
print("\nMultiplication (np.multiply):")
print(np.multiply(a, b))

# Division
print("\nDivision (np.divide):")
print(np.divide(a, b))

# Power
print("\nPower (np.power):")
print(np.power(a, b))

# Modulus
print("\nModulus (np.mod):")
print(np.mod(a, b))

# Floor Division
print("\nFloor Division (np.floor_divide):")
print(np.floor_divide(a, b))

# Absolute Difference
print("\nAbsolute Difference (np.abs):")
print(np.abs(a - b))

Array A: [10 20 30 40]
Array B: [1 2 3 4]

Addition (np.add):
[11 22 33 44]

Subtraction (np.subtract):
[ 9 18 27 36]

Multiplication (np.multiply):
[ 10  40  90 160]

Division (np.divide):
[10. 10. 10. 10.]

Power (np.power):
[     10     400   27000 2560000]

Modulus (np.mod):
[0 0 0 0]

Floor Division (np.floor_divide):
[10 10 10 10]

Absolute Difference (np.abs):
[ 9 18 27 36]


In [13]:
np.random.seed(121)
data=np.random.randint(0,100,10)
data

array([66, 85,  8, 95, 65, 52, 83, 96, 46, 34], dtype=int32)

In [14]:
np.min(data)

np.int32(8)

In [15]:
np.max(data)

np.int32(96)

In [16]:
np.mean(data)

np.float64(63.0)

In [17]:
np.median(data)

np.float64(65.5)

In [18]:
np.std(data)

np.float64(26.99259157620846)

In [19]:
True+1

2

In [20]:
data= np.array([10,20,np.nan,40,50,np.nan,70])
data

array([10., 20., nan, 40., 50., nan, 70.])

In [21]:
print("original data:", data)

original data: [10. 20. nan 40. 50. nan 70.]


In [22]:
print("null position:",np.isnan(data))

null position: [False False  True False False  True False]


In [23]:
print("tot null values:",np.isnan(data).sum())

tot null values: 2


In [24]:
clean_data=data[np.isnan(data)]
print("after removing null:", clean_data) 
data

after removing null: [nan nan]


array([10., 20., nan, 40., 50., nan, 70.])

In [25]:
replace_zero=np.nan_to_num(data,nan=0)
print("replace nan with 0:", replace_zero)

replace nan with 0: [10. 20.  0. 40. 50.  0. 70.]


In [26]:
# 5. Replace Null Values with Mean
mean_value = np.nanmean(data)
replace_mean = np.where(np.isnan(data), mean_value, data)
print("Replace NaN with Mean:", replace_mean)
# 6. Replace Null Values with Median
median_value = np.nanmedian(data)
replace_median = np.where(np.isnan(data), median_value, data)
print("Replace NaN with Median:", replace_median)

# 7. Replace Null Values with Custom Value
replace_custom = np.where(np.isnan(data), 999, data)
print("Replace NaN with Custom Value:", replace_custom)

# 8. Ignore Null Values in Calculations
print("Mean ignoring NaN:", np.nanmean(data))
print("Sum ignoring NaN:", np.nansum(data))
print("Std ignoring NaN:", np.nanstd(data))
print("Min ignoring NaN:", np.nanmin(data))
print("Max ignoring NaN:", np.nanmax(data))

Replace NaN with Mean: [10. 20. 38. 40. 50. 38. 70.]
Replace NaN with Median: [10. 20. 40. 40. 50. 40. 70.]
Replace NaN with Custom Value: [ 10.  20. 999.  40.  50. 999.  70.]
Mean ignoring NaN: 38.0
Sum ignoring NaN: 190.0
Std ignoring NaN: 21.354156504062622
Min ignoring NaN: 10.0
Max ignoring NaN: 70.0
